[pyprland]
plugins = ["scratchpads", "expose"]

[scratchpads.drop-term]
animation = "fromBottom"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
lazy = true
position = "25% 48%"
size = "50% 50%"
# unfocus = "hide"

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
lazy = true
size = "40% 90%"
unfocus = "hide"

[scratchpads.chrome]
animation = "fromLeft"
command = "chromium"
class = "Chromium"
lazy = true
size = "50% 90%"

[expose]
include_special = false
